import type { BusinessBlueprint, Lead } from "./business.types";

export const businesses: BusinessBlueprint[] = [
  {
    id: "biz_01",
    slug: "smilecraft-dental-bandra",
    industry: "dental",
    status: "generated",
    generatedAt: "2026-07-28",
    name: "SmileCraft Dental Studio",
    tagline: "Bandra's calm, precise dental care",
    category: "Dental Clinic",
    description:
      "SmileCraft Dental Studio is a boutique clinic in Bandra West where digital dentistry meets an unhurried, hospitality-led experience. Twelve years, forty thousand smiles, one standard of care.",
    address: "3rd Floor, Turner Road, Bandra West, Mumbai 400050",
    landmarks: ["Opposite Bandra Talkies", "5 min from Bandra Station"],
    city: "Mumbai",
    phone: "+91 98200 41122",
    whatsapp: "919820041122",
    email: "care@smilecraftdental.in",
    mapEmbedQuery: "Turner Road, Bandra West, Mumbai",
    hours: [
      { day: "Monday – Friday", open: "10:00 – 20:00" },
      { day: "Saturday", open: "10:00 – 18:00" },
      { day: "Sunday", open: "By appointment" },
    ],
    logoMark: "SC",
    brand: { primary: "oklch(0.47 0.088 197)", accent: "oklch(0.93 0.045 82)" },
    photos: [],
    services: [
      { id: "s1", name: "Invisible Aligners", description: "Digitally planned clear aligners with 3D outcome preview before you begin.", priceFrom: "₹85,000", duration: "6–14 months" },
      { id: "s2", name: "Single-Visit Root Canal", description: "Rotary endodontics under magnification — most cases finished in one sitting.", priceFrom: "₹6,500", duration: "60–90 min" },
      { id: "s3", name: "Dental Implants", description: "Guided implant surgery with same-day temporary crowns.", priceFrom: "₹32,000", duration: "2 visits" },
      { id: "s4", name: "Smile Design", description: "Ceramic veneers planned on a digital mock-up you approve first.", priceFrom: "₹18,000", duration: "3 visits" },
      { id: "s5", name: "Kids Dentistry", description: "Gentle, fear-free care with a dedicated paediatric chair and play corner.", priceFrom: "₹1,500", duration: "30 min" },
      { id: "s6", name: "Scaling & Whitening", description: "Ultrasonic cleaning plus in-chair whitening in a single appointment.", priceFrom: "₹3,000", duration: "45 min" },
    ],
    team: [
      { id: "d1", name: "Dr. Ananya Mehta", role: "Founder & Prosthodontist", qualification: "MDS, Prosthodontics", experience: "14 years", bio: "Trained at Nair Hospital and certified in digital smile design, Dr. Mehta leads all full-mouth rehabilitation cases.", photo: "" },
      { id: "d2", name: "Dr. Rohan Kulkarni", role: "Endodontist", qualification: "MDS, Endodontics", experience: "9 years", bio: "Micro-endodontics specialist, known for painless single-visit root canals.", photo: "" },
      { id: "d3", name: "Dr. Sara Fernandes", role: "Paediatric Dentist", qualification: "MDS, Pedodontics", experience: "7 years", bio: "Makes first dental visits something children actually look forward to.", photo: "" },
    ],
    faqs: [
      { id: "f1", question: "Do you accept walk-ins?", answer: "We keep two emergency slots open every day. For everything else, booking ahead keeps your waiting time under ten minutes." },
      { id: "f2", question: "Is treatment painful?", answer: "We use topical numbing before every injection and magnification for precision. Most patients describe procedures as pressure, not pain." },
      { id: "f3", question: "Do you offer EMI?", answer: "Yes — zero-cost EMI on treatments above ₹20,000 across major cards." },
      { id: "f4", question: "Which insurance do you support?", answer: "We provide detailed treatment invoices accepted by all major reimbursement providers." },
    ],
    reviews: {
      rating: 4.9,
      count: 486,
      summary:
        "Patients consistently mention the painless procedures, on-time appointments and how clearly the team explains treatment options before starting.",
      items: [
        { id: "r1", author: "Priya N.", rating: 5, text: "Finally a clinic that runs on time. Dr. Mehta explained my aligner plan with a 3D preview — no guesswork.", source: "Google", date: "3 weeks ago" },
        { id: "r2", author: "Aditya S.", rating: 5, text: "Root canal in one visit and I genuinely felt nothing. The place is spotless.", source: "Google", date: "1 month ago" },
        { id: "r3", author: "Meher K.", rating: 5, text: "My 6-year-old asked when we're going back. That says everything.", source: "Google", date: "2 months ago" },
      ],
    },
    cta: { primary: "Book an appointment", secondary: "Call the clinic" },
    seo: {
      title: "SmileCraft Dental Studio — Dentist in Bandra West, Mumbai",
      keywords: ["dentist in Bandra", "dental clinic Mumbai", "invisible aligners Bandra", "root canal Mumbai"],
      metaDescription:
        "Boutique dental clinic in Bandra West, Mumbai. Invisible aligners, single-visit root canals, implants and smile design. Rated 4.9 by 486 patients.",
    },
    social: [
      { label: "Instagram", url: "#" },
      { label: "Facebook", url: "#" },
    ],
    personality: ["Calm", "Precise", "Premium", "Reassuring"],
    audience: "Working professionals and families in Bandra, Khar and Santacruz seeking unhurried, high-quality dental care.",
    usp: ["Same-day appointments", "Digital treatment previews", "Single-visit root canals", "Zero-cost EMI"],
    trust: [
      { label: "Patients treated", value: "40,000+" },
      { label: "Google rating", value: "4.9 / 5" },
      { label: "Years in Bandra", value: "12" },
      { label: "Sterilisation", value: "ISO protocol" },
    ],
  },
  {
    id: "biz_02",
    slug: "pearl-avenue-dental-andheri",
    industry: "dental",
    status: "in-review",
    generatedAt: "2026-07-30",
    name: "Pearl Avenue Dental",
    tagline: "Family dentistry in Andheri West",
    category: "Dental Clinic",
    description: "A family-first dental practice serving Andheri West for over a decade.",
    address: "Lokhandwala Complex, Andheri West, Mumbai 400053",
    landmarks: ["Near Infiniti Mall"],
    city: "Mumbai",
    phone: "+91 98670 22110",
    whatsapp: "919867022110",
    email: "hello@pearlavenue.in",
    mapEmbedQuery: "Lokhandwala Complex, Andheri West, Mumbai",
    hours: [
      { day: "Monday – Saturday", open: "09:30 – 19:30" },
      { day: "Sunday", open: "Closed" },
    ],
    logoMark: "PA",
    brand: { primary: "oklch(0.47 0.088 197)", accent: "oklch(0.93 0.045 82)" },
    photos: [],
    services: [
      { id: "s1", name: "Braces & Aligners", description: "Metal, ceramic and clear aligner options for teens and adults.", priceFrom: "₹45,000" },
      { id: "s2", name: "Crowns & Bridges", description: "Zirconia crowns milled in-house.", priceFrom: "₹9,000" },
      { id: "s3", name: "Gum Treatment", description: "Laser-assisted periodontal therapy.", priceFrom: "₹4,000" },
    ],
    team: [
      { id: "d1", name: "Dr. Vikram Shah", role: "Chief Dentist", qualification: "BDS, MDS", experience: "16 years", bio: "Orthodontics lead with a focus on adult aligner cases.", photo: "" },
    ],
    faqs: [{ id: "f1", question: "Do you treat children?", answer: "Yes, from age three upwards." }],
    reviews: {
      rating: 4.7,
      count: 212,
      summary: "Reviewers highlight friendly staff, fair pricing and short waiting times.",
      items: [{ id: "r1", author: "Nikhil D.", rating: 5, text: "Straightforward advice, no upselling.", source: "Google", date: "2 weeks ago" }],
    },
    cta: { primary: "Book a visit", secondary: "Call now" },
    seo: {
      title: "Pearl Avenue Dental — Dentist in Andheri West, Mumbai",
      keywords: ["dentist Andheri", "braces Mumbai"],
      metaDescription: "Family dental clinic in Lokhandwala, Andheri West. Braces, crowns and gum care.",
    },
    social: [{ label: "Instagram", url: "#" }],
    personality: ["Friendly", "Practical", "Warm"],
    audience: "Families in Andheri West and Lokhandwala.",
    usp: ["Transparent pricing", "Evening slots"],
    trust: [
      { label: "Patients", value: "18,000+" },
      { label: "Rating", value: "4.7 / 5" },
      { label: "Years", value: "11" },
      { label: "Sterilisation", value: "Autoclave" },
    ],
  },
  {
    id: "biz_03",
    slug: "the-dental-loft-powai",
    industry: "dental",
    status: "published",
    generatedAt: "2026-07-19",
    name: "The Dental Loft",
    tagline: "Modern dentistry in Powai",
    category: "Dental Clinic",
    description: "A design-led dental studio inside Powai's business district.",
    address: "Hiranandani Gardens, Powai, Mumbai 400076",
    landmarks: ["Above Galleria Market"],
    city: "Mumbai",
    phone: "+91 99304 55123",
    whatsapp: "919930455123",
    email: "studio@dentalloft.in",
    mapEmbedQuery: "Hiranandani Gardens, Powai, Mumbai",
    hours: [{ day: "Monday – Sunday", open: "10:00 – 21:00" }],
    logoMark: "DL",
    brand: { primary: "oklch(0.47 0.088 197)", accent: "oklch(0.93 0.045 82)" },
    photos: [],
    services: [
      { id: "s1", name: "Cosmetic Veneers", description: "Ultra-thin ceramic veneers.", priceFrom: "₹22,000" },
      { id: "s2", name: "Full Mouth Implants", description: "All-on-4 rehabilitation.", priceFrom: "₹2,80,000" },
    ],
    team: [{ id: "d1", name: "Dr. Kavita Rao", role: "Cosmetic Dentist", qualification: "MDS", experience: "12 years", bio: "Veneer and smile design specialist.", photo: "" }],
    faqs: [{ id: "f1", question: "Are you open on Sundays?", answer: "Yes, every day 10am to 9pm." }],
    reviews: {
      rating: 4.8,
      count: 341,
      summary: "Known for aesthetics-focused treatment and a calm studio environment.",
      items: [{ id: "r1", author: "Tanya M.", rating: 5, text: "The veneers look completely natural.", source: "Google", date: "1 week ago" }],
    },
    cta: { primary: "Reserve a chair", secondary: "WhatsApp us" },
    seo: {
      title: "The Dental Loft — Cosmetic Dentist in Powai, Mumbai",
      keywords: ["cosmetic dentist Powai", "veneers Mumbai"],
      metaDescription: "Design-led cosmetic dental studio in Hiranandani Gardens, Powai. Veneers, implants and smile design.",
    },
    social: [{ label: "Instagram", url: "#" }],
    personality: ["Design-led", "Precise", "Contemporary"],
    audience: "Professionals in Powai seeking cosmetic dentistry.",
    usp: ["Open all week", "In-house lab"],
    trust: [
      { label: "Smiles designed", value: "9,400+" },
      { label: "Rating", value: "4.8 / 5" },
      { label: "Years", value: "8" },
      { label: "Lab", value: "In-house" },
    ],
  },
];

export const leads: Lead[] = [
  { id: "l1", businessId: "biz_01", name: "Rhea Kapoor", phone: "+91 98111 22334", message: "Would like an aligner consultation this Saturday.", channel: "Appointment form", createdAt: "2 hours ago", status: "new" },
  { id: "l2", businessId: "biz_01", name: "Imran Sheikh", phone: "+91 98220 71234", message: "Severe tooth pain, need an emergency slot today.", channel: "WhatsApp", createdAt: "5 hours ago", status: "new" },
  { id: "l3", businessId: "biz_01", name: "Deepa Iyer", phone: "+91 90040 55621", message: "Asking about implant cost and EMI options.", channel: "Contact form", createdAt: "Yesterday", status: "contacted" },
  { id: "l4", businessId: "biz_01", name: "Karan Bhatia", phone: "+91 99870 11223", message: "Scaling appointment for two people.", channel: "Call", createdAt: "2 days ago", status: "closed" },
];
