/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminGenerateRouteImport } from './routes/admin.generate'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner.analytics'
import { Route as OwnerContactRouteImport } from './routes/owner.contact'
import { Route as OwnerDoctorsRouteImport } from './routes/owner.doctors'
import { Route as OwnerGalleryRouteImport } from './routes/owner.gallery'
import { Route as OwnerLeadsRouteImport } from './routes/owner.leads'
import { Route as OwnerPagesRouteImport } from './routes/owner.pages'
import { Route as OwnerSeoRouteImport } from './routes/owner.seo'
import { Route as OwnerServicesRouteImport } from './routes/owner.services'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as AdminBusinessesIndexRouteImport } from './routes/admin.businesses.index'
import { Route as AdminBusinessesIdRouteImport } from './routes/admin.businesses.$id'
import { Route as AdminPreviewSlugRouteImport } from './routes/admin.preview.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerateRoute = AdminGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerContactRoute = OwnerContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDoctorsRoute = OwnerDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerGalleryRoute = OwnerGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerLeadsRoute = OwnerLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPagesRoute = OwnerPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSeoRoute = OwnerSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerServicesRoute = OwnerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => OwnerRoute,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesIndexRoute = AdminBusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesIdRoute = AdminBusinessesIdRouteImport.update({
  id: '/businesses/$id',
  path: '/businesses/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewSlugRoute = AdminPreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/generate': typeof GenerateRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/contact': typeof OwnerContactRoute
  '/owner/doctors': typeof OwnerDoctorsRoute
  '/owner/gallery': typeof OwnerGalleryRoute
  '/owner/leads': typeof OwnerLeadsRoute
  '/owner/pages': typeof OwnerPagesRoute
  '/owner/seo': typeof OwnerSeoRoute
  '/owner/services': typeof OwnerServicesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/admin/businesses/': typeof AdminBusinessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/contact': typeof OwnerContactRoute
  '/owner/doctors': typeof OwnerDoctorsRoute
  '/owner/gallery': typeof OwnerGalleryRoute
  '/owner/leads': typeof OwnerLeadsRoute
  '/owner/pages': typeof OwnerPagesRoute
  '/owner/seo': typeof OwnerSeoRoute
  '/owner/services': typeof OwnerServicesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/admin/businesses': typeof AdminBusinessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/generate': typeof GenerateRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/contact': typeof OwnerContactRoute
  '/owner/doctors': typeof OwnerDoctorsRoute
  '/owner/gallery': typeof OwnerGalleryRoute
  '/owner/leads': typeof OwnerLeadsRoute
  '/owner/pages': typeof OwnerPagesRoute
  '/owner/seo': typeof OwnerSeoRoute
  '/owner/services': typeof OwnerServicesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/admin/businesses/': typeof AdminBusinessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/generate'
    | '/owner'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/generate'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/templates'
    | '/admin/users'
    | '/owner/analytics'
    | '/owner/contact'
    | '/owner/doctors'
    | '/owner/gallery'
    | '/owner/leads'
    | '/owner/pages'
    | '/owner/seo'
    | '/owner/services'
    | '/site/$slug'
    | '/admin/'
    | '/owner/'
    | '/admin/businesses/$id'
    | '/admin/preview/$slug'
    | '/admin/businesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generate'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/generate'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/templates'
    | '/admin/users'
    | '/owner/analytics'
    | '/owner/contact'
    | '/owner/doctors'
    | '/owner/gallery'
    | '/owner/leads'
    | '/owner/pages'
    | '/owner/seo'
    | '/owner/services'
    | '/site/$slug'
    | '/admin'
    | '/owner'
    | '/admin/businesses/$id'
    | '/admin/preview/$slug'
    | '/admin/businesses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/generate'
    | '/owner'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/generate'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/templates'
    | '/admin/users'
    | '/owner/analytics'
    | '/owner/contact'
    | '/owner/doctors'
    | '/owner/gallery'
    | '/owner/leads'
    | '/owner/pages'
    | '/owner/seo'
    | '/owner/services'
    | '/site/$slug'
    | '/admin/'
    | '/owner/'
    | '/admin/businesses/$id'
    | '/admin/preview/$slug'
    | '/admin/businesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GenerateRoute: typeof GenerateRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SiteSlugRoute: typeof SiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generate': {
      id: '/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AdminGenerateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/contact': {
      id: '/owner/contact'
      path: '/contact'
      fullPath: '/owner/contact'
      preLoaderRoute: typeof OwnerContactRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/doctors': {
      id: '/owner/doctors'
      path: '/doctors'
      fullPath: '/owner/doctors'
      preLoaderRoute: typeof OwnerDoctorsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/gallery': {
      id: '/owner/gallery'
      path: '/gallery'
      fullPath: '/owner/gallery'
      preLoaderRoute: typeof OwnerGalleryRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/leads': {
      id: '/owner/leads'
      path: '/leads'
      fullPath: '/owner/leads'
      preLoaderRoute: typeof OwnerLeadsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/pages': {
      id: '/owner/pages'
      path: '/pages'
      fullPath: '/owner/pages'
      preLoaderRoute: typeof OwnerPagesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/seo': {
      id: '/owner/seo'
      path: '/seo'
      fullPath: '/owner/seo'
      preLoaderRoute: typeof OwnerSeoRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/services': {
      id: '/owner/services'
      path: '/services'
      fullPath: '/owner/services'
      preLoaderRoute: typeof OwnerServicesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/businesses/': {
      id: '/admin/businesses/'
      path: '/businesses'
      fullPath: '/admin/businesses/'
      preLoaderRoute: typeof AdminBusinessesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses/$id': {
      id: '/admin/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/admin/businesses/$id'
      preLoaderRoute: typeof AdminBusinessesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview/$slug': {
      id: '/admin/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/admin/preview/$slug'
      preLoaderRoute: typeof AdminPreviewSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminGenerateRoute: typeof AdminGenerateRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBusinessesIdRoute: typeof AdminBusinessesIdRoute
  AdminPreviewSlugRoute: typeof AdminPreviewSlugRoute
  AdminBusinessesIndexRoute: typeof AdminBusinessesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminGenerateRoute: AdminGenerateRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBusinessesIdRoute: AdminBusinessesIdRoute,
  AdminPreviewSlugRoute: AdminPreviewSlugRoute,
  AdminBusinessesIndexRoute: AdminBusinessesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OwnerRouteChildren {
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerContactRoute: typeof OwnerContactRoute
  OwnerDoctorsRoute: typeof OwnerDoctorsRoute
  OwnerGalleryRoute: typeof OwnerGalleryRoute
  OwnerLeadsRoute: typeof OwnerLeadsRoute
  OwnerPagesRoute: typeof OwnerPagesRoute
  OwnerSeoRoute: typeof OwnerSeoRoute
  OwnerServicesRoute: typeof OwnerServicesRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerContactRoute: OwnerContactRoute,
  OwnerDoctorsRoute: OwnerDoctorsRoute,
  OwnerGalleryRoute: OwnerGalleryRoute,
  OwnerLeadsRoute: OwnerLeadsRoute,
  OwnerPagesRoute: OwnerPagesRoute,
  OwnerSeoRoute: OwnerSeoRoute,
  OwnerServicesRoute: OwnerServicesRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GenerateRoute: GenerateRoute,
  OwnerRoute: OwnerRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SiteSlugRoute: SiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
