import type { IndustryDesign, IndustryTheme, IndustryWords } from "./industry.types";

const baseWords: IndustryWords = {
  servicesNav: "Services",
  servicesEyebrow: "What we do",
  servicesTitle: "Everything we do, done properly",
  teamNav: "Team",
  teamEyebrow: "The team",
  teamTitle: "The people behind the work",
  galleryNav: "Gallery",
  galleryTitle: "A look inside",
  aboutTitle: "Why people choose us",
  contactEyebrow: "Get in touch",
  contactTitle: "Book a visit",
  ctaPrimary: "Book now",
  ctaSecondary: "Call us",
  newsletterTitle: "Occasional notes, worth opening",
};

const w = (o: Partial<IndustryWords>): IndustryWords => ({ ...baseWords, ...o });

const baseTheme: IndustryTheme = {
  background: "oklch(0.988 0.005 95)",
  foreground: "oklch(0.22 0.026 250)",
  primary: "oklch(0.47 0.088 197)",
  primaryForeground: "oklch(0.99 0.005 95)",
  accent: "oklch(0.93 0.045 82)",
  accentForeground: "oklch(0.3 0.05 60)",
  secondary: "oklch(0.957 0.012 95)",
  muted: "oklch(0.962 0.008 95)",
  mutedForeground: "oklch(0.52 0.02 250)",
  border: "oklch(0.9 0.01 95)",
  ink: "oklch(0.22 0.026 250)",
  sand: "oklch(0.94 0.03 80)",
  radius: "0.875rem",
  displayFont: '"Instrument Serif", ui-serif, Georgia, serif',
};

const t = (o: Partial<IndustryTheme>): IndustryTheme => ({ ...baseTheme, ...o });

const ALL: IndustryDesign[] = [
  {
    id: "dental",
    label: "Dental Clinic",
    category: "Dental Clinic",
    heroVariant: "split",
    sections: ["about", "services", "team", "gallery", "reviews", "faq", "contact"],
    theme: t({}),
    words: w({
      servicesNav: "Treatments", servicesEyebrow: "Treatments", servicesTitle: "Care planned before it begins",
      teamNav: "Doctors", teamEyebrow: "Your doctors", teamTitle: "Specialists you'll actually meet",
      galleryTitle: "Inside the clinic", contactEyebrow: "Appointments", contactTitle: "Book an appointment",
      ctaPrimary: "Book an appointment", ctaSecondary: "Call the clinic",
      newsletterTitle: "Dental care notes, twice a month",
    }),
    credibility: ["ISO-certified sterilisation", "Digital OPG on site", "Zero-cost EMI", "Same-day emergency slots", "Wheelchair accessible"],
    seed: {
      tagline: "Calm, precise dental care",
      blurb: "A boutique clinic where digital dentistry meets an unhurried, hospitality-led experience.",
      audience: "Families and professionals who want dentistry explained clearly, priced honestly and finished on time.",
      usp: ["Single-visit root canals", "3D-planned aligners", "Zero-cost EMI", "On-time appointments"],
      trust: [["Patients", "40,000+"], ["Rating", "4.9 / 5"], ["Years", "12"], ["Sterilised", "ISO"]],
      services: [
        ["Invisible Aligners", "Digitally planned clear aligners with a 3D outcome preview before you begin.", "₹85,000", "6–14 months"],
        ["Single-Visit Root Canal", "Rotary endodontics under magnification — most cases finished in one sitting.", "₹6,500", "60–90 min"],
        ["Dental Implants", "Guided implant surgery with same-day temporary crowns.", "₹32,000", "2 visits"],
        ["Smile Design", "Ceramic veneers planned on a digital mock-up you approve first.", "₹18,000", "3 visits"],
        ["Kids Dentistry", "Gentle, fear-free care with a dedicated paediatric chair.", "₹1,500", "30 min"],
        ["Scaling & Whitening", "Ultrasonic cleaning plus in-chair whitening in one appointment.", "₹3,000", "45 min"],
      ],
      team: [
        ["Dr. Ananya Mehta", "Founder & Prosthodontist", "MDS, Prosthodontics", "14 years", "Leads all full-mouth rehabilitation cases and digital smile design."],
        ["Dr. Rohan Kulkarni", "Endodontist", "MDS, Endodontics", "9 years", "Micro-endodontics specialist known for painless single-visit root canals."],
        ["Dr. Sara Fernandes", "Paediatric Dentist", "MDS, Pedodontics", "7 years", "Makes first dental visits something children look forward to."],
      ],
      faqs: [
        ["Do you accept walk-ins?", "We keep two emergency slots open daily. For everything else, booking ahead keeps waiting under ten minutes."],
        ["Is treatment painful?", "Topical numbing before every injection and magnification for precision. Most patients describe pressure, not pain."],
        ["Do you offer EMI?", "Yes — zero-cost EMI on treatments above ₹20,000 across major cards."],
      ],
      reviewSummary: "Patients consistently mention painless procedures, on-time appointments and how clearly treatment options are explained.",
      reviews: [["Priya N.", "Finally a clinic that runs on time. My aligner plan came with a 3D preview — no guesswork."], ["Aditya S.", "Root canal in one visit and I genuinely felt nothing. The place is spotless."]],
      gallery: ["Reception", "Consultation", "Sterilisation bay", "Patient lounge"],
      keywords: ["dentist", "dental clinic", "root canal", "aligners", "implants"],
    },
  },
  {
    id: "doctor",
    label: "Doctor / Clinic",
    category: "Medical Practice",
    heroVariant: "split",
    sections: ["about", "services", "team", "reviews", "faq", "gallery", "contact"],
    theme: t({ primary: "oklch(0.52 0.13 245)", accent: "oklch(0.92 0.05 210)", accentForeground: "oklch(0.3 0.06 245)", sand: "oklch(0.93 0.035 220)", background: "oklch(0.99 0.004 240)", radius: "0.75rem" }),
    words: w({
      servicesNav: "Specialities", servicesEyebrow: "Specialities", servicesTitle: "Evidence-led care, explained plainly",
      teamNav: "Doctors", teamEyebrow: "Consultants", teamTitle: "Consultants you can trust",
      galleryTitle: "Inside the practice", contactEyebrow: "Consultations", contactTitle: "Book a consultation",
      ctaPrimary: "Book a consultation", ctaSecondary: "Call reception",
      newsletterTitle: "Health notes from our consultants",
    }),
    credibility: ["NABH-aligned protocols", "Digital prescriptions", "Teleconsults available", "Cashless insurance desk", "In-house diagnostics"],
    seed: {
      tagline: "Unhurried medicine, modern diagnostics",
      blurb: "A neighbourhood practice built around long consults, honest second opinions and diagnostics under one roof.",
      audience: "Patients who want a doctor who listens, explains and follows up — not a five-minute queue.",
      usp: ["20-minute consultations", "Same-day reports", "Cashless insurance", "Follow-up on WhatsApp"],
      trust: [["Patients", "25,000+"], ["Rating", "4.8 / 5"], ["Years", "16"], ["Consultants", "6"]],
      services: [
        ["General Medicine", "Full diagnostic work-up with a written care plan you keep.", "₹800", "20 min"],
        ["Preventive Health Check", "Bloods, ECG and consult bundled into a single morning.", "₹3,500", "2 hours"],
        ["Diabetes & Thyroid Care", "Structured long-term management with quarterly reviews.", "₹1,000", "Ongoing"],
        ["Paediatrics", "Growth tracking, immunisation and reassurance for new parents.", "₹900", "25 min"],
        ["Cardiology Consult", "ECG, 2D echo and a clear risk explanation.", "₹1,500", "40 min"],
        ["Teleconsultation", "Video review of reports and prescription refills.", "₹500", "15 min"],
      ],
      team: [
        ["Dr. Meera Iyer", "Internal Medicine", "MD, Internal Medicine", "18 years", "Focuses on metabolic health and long-term chronic care."],
        ["Dr. Arjun Nair", "Cardiologist", "DM, Cardiology", "12 years", "Preventive cardiology and non-invasive diagnostics."],
        ["Dr. Neha Bhatt", "Paediatrician", "MD, Paediatrics", "10 years", "Gentle with anxious children and first-time parents alike."],
      ],
      faqs: [
        ["Do you accept insurance?", "Yes — our desk handles cashless approvals for all major insurers."],
        ["How long is a consultation?", "Twenty minutes minimum. We book fewer patients per hour on purpose."],
        ["Can I get reports online?", "Reports are sent by WhatsApp and email the same day."],
      ],
      reviewSummary: "Patients praise the unhurried consultations, clear explanations and how quickly reports come back.",
      reviews: [["Sanjay M.", "First doctor in years who actually explained my reports line by line."], ["Farah K.", "Booked at 10, seen at 10. Unheard of."]],
      gallery: ["Reception", "Consult room", "Diagnostics", "Waiting lounge"],
      keywords: ["doctor", "clinic", "physician", "health check", "consultation"],
    },
  },
  {
    id: "restaurant",
    label: "Restaurant",
    category: "Restaurant",
    heroVariant: "full",
    sections: ["services", "gallery", "about", "reviews", "team", "faq", "contact"],
    theme: t({ background: "oklch(0.16 0.012 60)", foreground: "oklch(0.96 0.012 80)", primary: "oklch(0.68 0.16 45)", primaryForeground: "oklch(0.16 0.012 60)", accent: "oklch(0.78 0.13 78)", accentForeground: "oklch(0.18 0.02 60)", secondary: "oklch(0.22 0.014 60)", muted: "oklch(0.22 0.014 60)", mutedForeground: "oklch(0.74 0.015 80)", border: "oklch(1 0 0 / 14%)", ink: "oklch(0.12 0.01 60)", sand: "oklch(0.35 0.06 60)", radius: "0.5rem", displayFont: '"Playfair Display", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Menu", servicesEyebrow: "The menu", servicesTitle: "Cooked to order, every order",
      teamNav: "Kitchen", teamEyebrow: "The kitchen", teamTitle: "The people at the pass",
      galleryNav: "Gallery", galleryTitle: "The room, the plates, the evenings",
      aboutTitle: "Why guests come back", contactEyebrow: "Reservations", contactTitle: "Reserve a table",
      ctaPrimary: "Reserve a table", ctaSecondary: "Call the restaurant",
      newsletterTitle: "New menus and one-night tables",
    }),
    credibility: ["Chef-led kitchen", "Seasonal produce", "Private dining room", "Full bar licence", "Valet parking"],
    seed: {
      tagline: "A room built for long dinners",
      blurb: "Modern Indian plates, an unfussy bar and a room that makes people stay for one more course.",
      audience: "Diners who want a proper night out — considered food, real hospitality, no rush to turn the table.",
      usp: ["Chef's tasting menu", "Sommelier-picked list", "Private dining for 20", "Open till midnight"],
      trust: [["Covers served", "1.2L+"], ["Rating", "4.7 / 5"], ["Years", "8"], ["Awards", "3"]],
      services: [
        ["Chef's Tasting Menu", "Seven courses built around whatever the market gave us this morning.", "₹3,200", "2.5 hours"],
        ["À la carte Dinner", "Small plates, robata grills and a short, sharp mains list.", "₹1,400", "Nightly"],
        ["Weekend Brunch", "Bottomless coffee, live counters and a lazy 3pm finish.", "₹1,800", "Sat–Sun"],
        ["Private Dining", "A separate room for twenty, with a bespoke menu.", "₹2,500 pp", "By booking"],
        ["Bar & Cocktails", "Fifteen house cocktails built on Indian spirits and produce.", "₹650", "Till 1am"],
        ["Event Catering", "Off-site menus for milestone dinners and small weddings.", "On request", "Custom"],
      ],
      team: [
        ["Chef Kabir Sethi", "Executive Chef", "Le Cordon Bleu", "15 years", "Cooked across London and Bengaluru before opening this kitchen."],
        ["Ritu Malhotra", "Head Sommelier", "WSET Level 3", "9 years", "Builds a list that leans Indian, Georgian and unexpected."],
        ["Imran Qureshi", "Head of Hospitality", "IHM Mumbai", "12 years", "Remembers your table, your drink and your anniversary."],
      ],
      faqs: [
        ["Do you take walk-ins?", "The bar counter is always walk-in. Tables are best reserved by 6pm."],
        ["Are there vegetarian options?", "Half the menu is vegetarian, and the tasting menu has a full veg version."],
        ["Can you host private events?", "Yes — the private room seats twenty, and full buy-outs are possible on Mondays."],
      ],
      reviewSummary: "Guests talk about the tasting menu, the cocktails and a service team that never hovers but never disappears.",
      reviews: [["Nikhil R.", "The tasting menu is the best value fine dining in the city right now."], ["Aparna D.", "We stayed three hours and nobody rushed us once."]],
      gallery: ["The dining room", "At the pass", "House cocktails", "Private room"],
      keywords: ["restaurant", "fine dining", "reservations", "tasting menu", "bar"],
    },
  },
  {
    id: "hotel",
    label: "Hotel",
    category: "Hotel",
    heroVariant: "full",
    sections: ["services", "gallery", "about", "reviews", "faq", "team", "contact"],
    theme: t({ background: "oklch(0.985 0.006 90)", foreground: "oklch(0.24 0.03 260)", primary: "oklch(0.32 0.06 260)", primaryForeground: "oklch(0.98 0.01 90)", accent: "oklch(0.82 0.1 85)", accentForeground: "oklch(0.28 0.05 70)", secondary: "oklch(0.95 0.012 88)", muted: "oklch(0.955 0.01 88)", mutedForeground: "oklch(0.5 0.02 260)", border: "oklch(0.89 0.012 88)", ink: "oklch(0.2 0.03 260)", sand: "oklch(0.9 0.05 85)", radius: "0.25rem", displayFont: '"Cormorant Garamond", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Rooms", servicesEyebrow: "Rooms & suites", servicesTitle: "Rooms that earn the stay",
      teamNav: "Team", teamEyebrow: "Hospitality", teamTitle: "The team on duty",
      galleryTitle: "The property", aboutTitle: "Why guests return", contactEyebrow: "Reservations", contactTitle: "Check availability",
      ctaPrimary: "Book your stay", ctaSecondary: "Call reservations",
      newsletterTitle: "Seasonal offers, sent rarely",
    }),
    credibility: ["24-hour concierge", "Airport transfers", "All-day dining", "Business centre", "Pet friendly"],
    seed: {
      tagline: "A quiet address in a loud city",
      blurb: "Forty-two rooms, an all-day restaurant and a service team that remembers how you take your coffee.",
      audience: "Business travellers and weekenders who want calm, clean design and genuinely quick service.",
      usp: ["Late 2pm checkout", "Complimentary transfers", "Rooftop pool", "Best-rate guarantee"],
      trust: [["Rooms", "42"], ["Rating", "4.8 / 5"], ["Years", "11"], ["Repeat guests", "62%"]],
      services: [
        ["Deluxe King", "Thirty-two square metres, blackout drapes, city view.", "₹7,500", "Per night"],
        ["Executive Suite", "Separate living room, lounge access and evening canapés.", "₹14,000", "Per night"],
        ["Long-stay Apartment", "Kitchenette and weekly housekeeping for stays over a fortnight.", "₹1,60,000", "Per month"],
        ["Meetings & Boardroom", "Twelve-seat boardroom with catering and AV.", "₹12,000", "Per day"],
        ["Spa & Pool", "Rooftop pool with a two-treatment-room spa.", "₹2,500", "Per session"],
        ["Weddings & Events", "Terrace and ballroom for up to 250 guests.", "On request", "Custom"],
      ],
      team: [
        ["Rohan Desai", "General Manager", "IHM Aurangabad", "20 years", "Ran city hotels across three states before taking this one on."],
        ["Sneha Kulkarni", "Head of Guest Relations", "Hospitality Management", "11 years", "Handles every special request personally."],
        ["Chef Alok Menon", "Executive Chef", "CIA Certified", "14 years", "Runs the all-day restaurant and banquet kitchens."],
      ],
      faqs: [
        ["What is the checkout time?", "Noon as standard, and 2pm free of charge whenever the house allows."],
        ["Do you provide airport transfers?", "Complimentary on suites and available on request for all other rooms."],
        ["Is parking available?", "Yes — valet parking is complimentary for in-house guests."],
      ],
      reviewSummary: "Guests highlight the quiet rooms, the breakfast and a front desk that solves things before you ask twice.",
      reviews: [["Deepak S.", "Quietest hotel room I've had in this city. Breakfast is excellent."], ["Laura W.", "They upgraded us and arranged a late checkout without being asked."]],
      gallery: ["The lobby", "Deluxe king", "Rooftop pool", "All-day dining"],
      keywords: ["hotel", "rooms", "stay", "business hotel", "booking"],
    },
  },
  {
    id: "resort",
    label: "Resort",
    category: "Resort",
    heroVariant: "full",
    sections: ["services", "gallery", "about", "reviews", "faq", "team", "contact"],
    theme: t({ background: "oklch(0.985 0.012 150)", foreground: "oklch(0.24 0.03 180)", primary: "oklch(0.5 0.09 180)", accent: "oklch(0.88 0.07 100)", accentForeground: "oklch(0.3 0.05 120)", secondary: "oklch(0.95 0.02 150)", muted: "oklch(0.955 0.015 150)", mutedForeground: "oklch(0.5 0.02 180)", border: "oklch(0.89 0.015 150)", ink: "oklch(0.22 0.03 180)", sand: "oklch(0.92 0.05 95)", radius: "1.5rem", displayFont: '"Cormorant Garamond", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Stays", servicesEyebrow: "Stays & experiences", servicesTitle: "Slow days, planned properly",
      teamNav: "Team", teamTitle: "Your hosts", galleryTitle: "Around the property",
      aboutTitle: "Why families come back", contactEyebrow: "Reservations", contactTitle: "Plan your escape",
      ctaPrimary: "Plan your stay", ctaSecondary: "Call the resort",
      newsletterTitle: "Long-weekend offers",
    }),
    credibility: ["Beachfront access", "All-inclusive plans", "Kids' club", "Ayurvedic spa", "Airport pickup"],
    seed: {
      tagline: "Where the weekend actually slows down",
      blurb: "Eleven acres of green, a beachfront lawn and a kitchen that keeps feeding you long after check-in.",
      audience: "Families and couples escaping the city for two nights that feel like five.",
      usp: ["All-inclusive plans", "Private villa pools", "Guided nature walks", "Kids' club all day"],
      trust: [["Acres", "11"], ["Rating", "4.9 / 5"], ["Villas", "36"], ["Repeat guests", "58%"]],
      services: [
        ["Garden Villa", "Private deck opening onto the lawn, outdoor shower.", "₹12,000", "Per night"],
        ["Pool Villa", "Plunge pool, daybed and dedicated butler service.", "₹22,000", "Per night"],
        ["All-Inclusive Plan", "All meals, activities and evening entertainment bundled.", "₹6,500", "Per person"],
        ["Ayurvedic Spa", "Traditional therapies in open-air treatment pavilions.", "₹3,500", "90 min"],
        ["Destination Weddings", "Lawn, beach and banquet across three days.", "On request", "Custom"],
        ["Corporate Offsites", "Meeting barn, team activities and full-board stays.", "On request", "Custom"],
      ],
      team: [
        ["Kabir Nambiar", "Resort Manager", "Hospitality Management", "17 years", "Grew up on this coast and runs the property like a home."],
        ["Anita Prabhu", "Head of Experiences", "Naturalist Certified", "8 years", "Designs the walks, workshops and evening programming."],
        ["Chef Dev Raut", "Executive Chef", "Culinary Institute", "13 years", "Cooks a coastal menu from a boat that lands each morning."],
      ],
      faqs: [
        ["Is the resort family friendly?", "Very — the kids' club runs all day and villas connect for larger families."],
        ["Do you offer airport transfers?", "Yes, on request, with an air-conditioned sedan or tempo traveller."],
        ["Can we host a wedding?", "We host up to 300 guests across the lawn and beach."],
      ],
      reviewSummary: "Guests mention the greenery, the food and staff who somehow anticipate what the children need next.",
      reviews: [["Ritu B.", "The pool villa was worth every rupee. We didn't leave the property once."], ["Ganesh V.", "Best coastal food I've had at a resort, and the staff adore the kids."]],
      gallery: ["The lawn", "Pool villa", "Spa pavilion", "Beachfront dining"],
      keywords: ["resort", "villa", "weekend getaway", "spa", "family holiday"],
    },
  },
  {
    id: "banquet",
    label: "Banquet Hall",
    category: "Banquet Hall",
    heroVariant: "editorial",
    sections: ["services", "gallery", "about", "reviews", "faq", "team", "contact"],
    theme: t({ background: "oklch(0.19 0.03 320)", foreground: "oklch(0.96 0.012 320)", primary: "oklch(0.78 0.12 85)", primaryForeground: "oklch(0.19 0.03 320)", accent: "oklch(0.62 0.15 340)", accentForeground: "oklch(0.98 0.01 320)", secondary: "oklch(0.25 0.035 320)", muted: "oklch(0.25 0.035 320)", mutedForeground: "oklch(0.76 0.02 320)", border: "oklch(1 0 0 / 15%)", ink: "oklch(0.14 0.03 320)", sand: "oklch(0.4 0.07 330)", radius: "0.375rem", displayFont: '"Playfair Display", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Spaces", servicesEyebrow: "Our spaces", servicesTitle: "Rooms that hold a whole celebration",
      teamNav: "Team", teamTitle: "Your event team", galleryTitle: "Recent celebrations",
      aboutTitle: "Why families book us", contactEyebrow: "Bookings", contactTitle: "Check your date",
      ctaPrimary: "Check availability", ctaSecondary: "Call the banquet desk",
      newsletterTitle: "Season dates and offers",
    }),
    credibility: ["Up to 1,200 guests", "In-house catering", "Valet for 200 cars", "Bridal suite", "Full power backup"],
    seed: {
      tagline: "Celebrations that run to the minute",
      blurb: "Three pillarless halls, a kitchen that cooks for a thousand and a team that has done this nine hundred times.",
      audience: "Families planning weddings, receptions and milestone functions who need it to simply work.",
      usp: ["Pillarless halls", "In-house catering", "Décor partners on site", "Dedicated event manager"],
      trust: [["Events hosted", "900+"], ["Max guests", "1,200"], ["Halls", "3"], ["Rating", "4.8 / 5"]],
      services: [
        ["Grand Ballroom", "Pillarless, 1,200 guests, twenty-foot ceilings.", "₹4,50,000", "Per day"],
        ["Terrace Lawn", "Open-air mandap setting for 600 with rain cover.", "₹2,80,000", "Per day"],
        ["Crystal Hall", "Intimate 250-guest room for receptions and sangeets.", "₹1,40,000", "Per day"],
        ["Catering Packages", "Multi-cuisine live counters, veg and non-veg menus.", "₹1,450 pp", "Per plate"],
        ["Décor & Mandap", "Floral, drape and lighting design with our partner studios.", "On request", "Custom"],
        ["Corporate Conferences", "Theatre seating for 800 with full AV.", "₹1,80,000", "Per day"],
      ],
      team: [
        ["Manish Agarwal", "Banquet Director", "IHM Delhi", "22 years", "Has run more than nine hundred weddings without a delayed muhurat."],
        ["Priya Shetty", "Event Manager", "Event Management", "10 years", "Your single point of contact from booking to bidaai."],
        ["Chef Salim Ansari", "Banquet Chef", "Culinary Arts", "18 years", "Cooks for a thousand without dropping a standard."],
      ],
      faqs: [
        ["Can we bring our own caterer?", "Our kitchen handles catering, but royalty arrangements are possible for specific communities."],
        ["Is parking available?", "Valet parking for 200 cars plus an overflow lot next door."],
        ["How early should we book?", "Peak season dates are usually taken nine to twelve months ahead."],
      ],
      reviewSummary: "Families mention the punctual service, the food quality at scale and an event manager who never disappears.",
      reviews: [["Sunita J.", "Nine hundred guests and not one complaint about the food. Remarkable."], ["Rakesh T.", "They handled a last-minute rain plan without us even noticing."]],
      gallery: ["Grand ballroom", "Mandap setup", "Live counters", "Bridal suite"],
      keywords: ["banquet hall", "wedding venue", "reception", "catering", "event space"],
    },
  },
  {
    id: "event",
    label: "Event Planner",
    category: "Event Planning Studio",
    heroVariant: "editorial",
    sections: ["services", "gallery", "about", "team", "reviews", "faq", "contact"],
    theme: t({ background: "oklch(0.15 0.03 300)", foreground: "oklch(0.97 0.01 300)", primary: "oklch(0.68 0.2 305)", primaryForeground: "oklch(0.15 0.03 300)", accent: "oklch(0.75 0.17 195)", accentForeground: "oklch(0.16 0.03 300)", secondary: "oklch(0.21 0.035 300)", muted: "oklch(0.21 0.035 300)", mutedForeground: "oklch(0.75 0.02 300)", border: "oklch(1 0 0 / 14%)", ink: "oklch(0.11 0.03 300)", sand: "oklch(0.34 0.08 300)", radius: "1.25rem", displayFont: '"Space Grotesk", ui-sans-serif, system-ui, sans-serif' }),
    words: w({
      servicesNav: "What we do", servicesEyebrow: "Capabilities", servicesTitle: "Events, engineered end to end",
      teamNav: "Studio", teamEyebrow: "The studio", teamTitle: "The people running the floor",
      galleryNav: "Work", galleryTitle: "Selected work", aboutTitle: "Why brands hire us",
      contactEyebrow: "Briefs", contactTitle: "Send us a brief",
      ctaPrimary: "Start a brief", ctaSecondary: "Call the studio",
      newsletterTitle: "Case studies, once a quarter",
    }),
    credibility: ["Pan-India production", "In-house AV", "500+ events delivered", "Vendor network of 200", "Live show calling"],
    seed: {
      tagline: "Events that look effortless because they aren't",
      blurb: "A production studio that runs conferences, launches and celebrations with show-caller precision.",
      audience: "Brands and families who need one accountable partner instead of eleven vendors.",
      usp: ["Single accountable producer", "In-house AV and rigging", "Run-of-show to the second", "Transparent budgets"],
      trust: [["Events", "500+"], ["Cities", "14"], ["Team", "35"], ["Rating", "4.9 / 5"]],
      services: [
        ["Corporate Conferences", "Content, stage design, AV and delegate management.", "₹8,00,000", "Per event"],
        ["Product Launches", "Concept, build, press choreography and content capture.", "₹5,00,000", "Per event"],
        ["Weddings & Sangeets", "Multi-day production with décor, artists and hospitality.", "₹15,00,000", "Per wedding"],
        ["Artist & Talent Booking", "Curated line-ups with contracts and riders handled.", "On request", "Custom"],
        ["Stage & Set Design", "3D renders, fabrication drawings and on-site build.", "₹2,50,000", "Per build"],
        ["Hybrid & Livestream", "Multi-cam production with broadcast-quality streaming.", "₹3,00,000", "Per event"],
      ],
      team: [
        ["Zara Khan", "Founder & Executive Producer", "Event Management", "16 years", "Has show-called for audiences of twelve thousand."],
        ["Aman Bedi", "Head of Production", "Technical Direction", "12 years", "Owns rigging, power, safety and every build drawing."],
        ["Tanvi Rao", "Creative Director", "Design", "9 years", "Turns a brief into a stage the room photographs all night."],
      ],
      faqs: [
        ["Do you work outside your city?", "We produce across fourteen cities with a travelling core team."],
        ["How are budgets structured?", "Line-item transparent, with production fee stated separately."],
        ["How early should we brief you?", "Six to eight weeks for corporate, four months for weddings."],
      ],
      reviewSummary: "Clients highlight the calm on show day, the transparency in budgets and how nothing slips through the cracks.",
      reviews: [["Vikram A.", "Twelve hundred delegates, four stages, zero incidents. They are ruthless about the run-of-show."], ["Nidhi P.", "The only vendor who told us where to save money."]],
      gallery: ["Main stage", "Build day", "Show calling", "Guest arrival"],
      keywords: ["event planner", "event management", "production", "conference", "launch"],
    },
  },
  {
    id: "wedding",
    label: "Wedding Planner",
    category: "Wedding Planning Studio",
    heroVariant: "editorial",
    sections: ["gallery", "services", "about", "reviews", "team", "faq", "contact"],
    theme: t({ background: "oklch(0.985 0.012 30)", foreground: "oklch(0.28 0.03 20)", primary: "oklch(0.58 0.1 20)", accent: "oklch(0.87 0.06 35)", accentForeground: "oklch(0.32 0.06 25)", secondary: "oklch(0.96 0.015 30)", muted: "oklch(0.965 0.012 30)", mutedForeground: "oklch(0.52 0.025 20)", border: "oklch(0.9 0.015 30)", ink: "oklch(0.26 0.04 20)", sand: "oklch(0.93 0.04 35)", radius: "2rem", displayFont: '"Cormorant Garamond", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Services", servicesEyebrow: "How we help", servicesTitle: "From the first list to the last dance",
      teamNav: "Planners", teamTitle: "Your planning team", galleryNav: "Weddings", galleryTitle: "Weddings we've planned",
      aboutTitle: "Why couples choose us", contactEyebrow: "Enquiries", contactTitle: "Tell us about your wedding",
      ctaPrimary: "Plan my wedding", ctaSecondary: "Call the studio",
      newsletterTitle: "Real weddings, in your inbox",
    }),
    credibility: ["Destination weddings", "Vendor negotiation", "Guest logistics", "Day-of coordination", "Budget transparency"],
    seed: {
      tagline: "Your wedding, without the worry",
      blurb: "Full-service planning for couples who want the celebration they imagined and the calm they deserve.",
      audience: "Couples and families planning multi-day weddings across India and abroad.",
      usp: ["One planner, start to finish", "Vetted vendor network", "Guest travel handled", "Honest budget tracking"],
      trust: [["Weddings", "180+"], ["Destinations", "22"], ["Rating", "5.0 / 5"], ["Years", "9"]],
      services: [
        ["Full Planning", "Everything from venue hunting to the send-off, twelve months out.", "₹6,00,000", "Per wedding"],
        ["Destination Weddings", "Venue recce, guest travel, permits and local vendor management.", "₹10,00,000", "Per wedding"],
        ["Partial Planning", "You've started; we take over three months before the date.", "₹3,00,000", "Per wedding"],
        ["Day-of Coordination", "A producer and crew who run the day so your family doesn't.", "₹1,20,000", "Per event"],
        ["Décor Direction", "Mood boards, florals and mandap design with our studios.", "On request", "Custom"],
        ["Guest Experience", "Hampers, transfers, room allocation and welcome desks.", "₹1,500 pp", "Per guest"],
      ],
      team: [
        ["Ishita Malhotra", "Founder & Lead Planner", "Wedding Planning", "12 years", "Has planned weddings across five countries and never missed a muhurat."],
        ["Aarav Menon", "Production Head", "Event Production", "10 years", "Runs the build, the crew and the timeline."],
        ["Ruhi Sen", "Guest Experience Lead", "Hospitality", "7 years", "Knows where every one of your four hundred guests should be."],
      ],
      faqs: [
        ["How far ahead should we start?", "Nine to twelve months for destination weddings, six for city weddings."],
        ["How do you charge?", "A flat planning fee, with all vendor costs passed through at actuals."],
        ["Do you travel?", "Yes — twenty-two destinations so far, and counting."],
      ],
      reviewSummary: "Couples describe a planning process that felt calm, budgets that stayed honest and families who actually enjoyed the wedding.",
      reviews: [["Meghna & Arjun", "Our mothers danced instead of managing vendors. That was the whole point."], ["Sara & Yusuf", "Three days, two cities, zero chaos."]],
      gallery: ["Mandap", "Sangeet night", "Guest welcome", "The send-off"],
      keywords: ["wedding planner", "destination wedding", "wedding decor", "wedding coordination"],
    },
  },
  {
    id: "photographer",
    label: "Photographer",
    category: "Photography Studio",
    heroVariant: "full",
    sections: ["gallery", "services", "about", "reviews", "team", "faq", "contact"],
    theme: t({ background: "oklch(0.145 0 0)", foreground: "oklch(0.97 0 0)", primary: "oklch(0.97 0 0)", primaryForeground: "oklch(0.145 0 0)", accent: "oklch(0.75 0.14 65)", accentForeground: "oklch(0.15 0 0)", secondary: "oklch(0.2 0 0)", muted: "oklch(0.2 0 0)", mutedForeground: "oklch(0.72 0 0)", border: "oklch(1 0 0 / 14%)", ink: "oklch(0.1 0 0)", sand: "oklch(0.3 0 0)", radius: "0rem", displayFont: '"Space Grotesk", ui-sans-serif, system-ui, sans-serif' }),
    words: w({
      servicesNav: "Services", servicesEyebrow: "Commissions", servicesTitle: "What we shoot",
      teamNav: "Studio", teamTitle: "Behind the camera", galleryNav: "Work", galleryTitle: "Selected frames",
      aboutTitle: "Why clients commission us", contactEyebrow: "Enquiries", contactTitle: "Check your date",
      ctaPrimary: "Check availability", ctaSecondary: "Call the studio",
      newsletterTitle: "New work, occasionally",
    }),
    credibility: ["Full-frame kit", "Same-week previews", "Print-ready delivery", "Drone licensed", "Backup shooter included"],
    seed: {
      tagline: "Frames you'll still print in twenty years",
      blurb: "A documentary-led studio shooting weddings, portraits and brand work with restraint and real light.",
      audience: "Clients who want honest photographs, not posed catalogues.",
      usp: ["Documentary approach", "Two shooters as standard", "Previews in seven days", "Archival prints"],
      trust: [["Weddings", "240+"], ["Frames delivered", "1.4M"], ["Years", "11"], ["Rating", "5.0 / 5"]],
      services: [
        ["Wedding Coverage", "Two photographers, full-day documentary coverage, 800 edited frames.", "₹1,80,000", "Per day"],
        ["Pre-wedding Shoot", "Half day on location with styling direction.", "₹65,000", "4 hours"],
        ["Portraits", "Studio or environmental portraits with retouching.", "₹18,000", "90 min"],
        ["Brand & Product", "Catalogue, lookbook and campaign photography.", "₹45,000", "Per day"],
        ["Film & Reels", "Cinematic highlight films and social cutdowns.", "₹1,20,000", "Per day"],
        ["Albums & Prints", "Hand-bound fine-art albums and archival prints.", "₹35,000", "Per album"],
      ],
      team: [
        ["Kabir Sen", "Principal Photographer", "Fine Art Photography", "13 years", "Shoots quietly and never asks anyone to look at the camera."],
        ["Anjali Verma", "Second Shooter & Editor", "Visual Communication", "8 years", "Colour grades every frame that leaves the studio."],
        ["Rehan Patel", "Filmmaker", "Cinematography", "9 years", "Cuts films that feel like memory, not montage."],
      ],
      faqs: [
        ["How soon do we get photos?", "Previews in seven days, the full gallery within five weeks."],
        ["Do you travel?", "Yes — travel and stay billed at actuals."],
        ["Do you shoot film?", "We shoot a roll or two of 120 on most weddings, included."],
      ],
      reviewSummary: "Clients talk about how invisible the team is on the day and how honest the photographs feel afterwards.",
      reviews: [["Tanya M.", "We forgot they were there, then cried at the gallery."], ["Rahul & Divya", "The film is the only wedding video our friends actually watched twice."]],
      gallery: ["Ceremony", "Portraits", "Details", "The party"],
      keywords: ["photographer", "wedding photography", "portraits", "photo studio"],
    },
  },
  {
    id: "decorator",
    label: "Decorator",
    category: "Décor Studio",
    heroVariant: "editorial",
    sections: ["gallery", "services", "about", "reviews", "team", "faq", "contact"],
    theme: t({ background: "oklch(0.985 0.012 60)", foreground: "oklch(0.26 0.03 30)", primary: "oklch(0.6 0.14 30)", accent: "oklch(0.72 0.11 145)", accentForeground: "oklch(0.98 0.01 145)", secondary: "oklch(0.96 0.018 60)", muted: "oklch(0.965 0.014 60)", mutedForeground: "oklch(0.5 0.025 30)", border: "oklch(0.9 0.018 60)", ink: "oklch(0.24 0.04 30)", sand: "oklch(0.93 0.05 60)", radius: "1.75rem", displayFont: '"Playfair Display", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Services", servicesEyebrow: "What we design", servicesTitle: "Décor built for the photograph and the room",
      teamNav: "Studio", teamTitle: "The design team", galleryNav: "Work", galleryTitle: "Recent setups",
      aboutTitle: "Why planners call us", contactEyebrow: "Enquiries", contactTitle: "Tell us about the event",
      ctaPrimary: "Request a quote", ctaSecondary: "Call the studio",
      newsletterTitle: "New setups and seasonal themes",
    }),
    credibility: ["In-house fabrication", "Fresh flower sourcing", "Same-day teardown", "Lighting design", "3D renders before build"],
    seed: {
      tagline: "Rooms transformed, on time, on budget",
      blurb: "A décor studio that renders it first, builds it properly and strikes it before sunrise.",
      audience: "Wedding families, planners and brands who want décor that photographs as well as it looks.",
      usp: ["3D render approval", "Own fabrication unit", "Fresh flowers daily", "Overnight teardown"],
      trust: [["Setups", "1,100+"], ["Crew", "60"], ["Years", "10"], ["Rating", "4.9 / 5"]],
      services: [
        ["Mandap & Stage", "Structure, drapes, florals and lighting as one design.", "₹2,50,000", "Per setup"],
        ["Floral Design", "Fresh flower walls, centrepieces and entrance arches.", "₹80,000", "Per setup"],
        ["Lighting & Ambience", "Architectural wash, festoon and pin-spot design.", "₹1,20,000", "Per venue"],
        ["Corporate Branding", "Backdrops, signage and brand activations.", "₹1,50,000", "Per event"],
        ["Home Functions", "Compact setups for pujas, birthdays and anniversaries.", "₹35,000", "Per setup"],
        ["Theme Design", "Concept boards, palettes and 3D renders before build.", "₹40,000", "Per concept"],
      ],
      team: [
        ["Nisha Rathore", "Creative Director", "Design", "14 years", "Draws every concept before it reaches the fabrication floor."],
        ["Sameer Joshi", "Production Head", "Fabrication", "11 years", "Runs a sixty-person crew and a workshop that never sleeps."],
        ["Fatima Sheikh", "Floral Lead", "Floristry", "8 years", "Sources fresh every morning from three markets."],
      ],
      faqs: [
        ["Do you provide 3D renders?", "Always. Nothing gets built before you approve the render."],
        ["Can you work in any venue?", "Yes, including heritage venues with rigging restrictions."],
        ["How quickly do you strike?", "Full teardown finishes before the venue's morning deadline."],
      ],
      reviewSummary: "Clients mention renders that matched reality, crews that arrived early and teardown nobody had to chase.",
      reviews: [["Preeti G.", "The mandap looked exactly like the render. Exactly."], ["Anand K.", "Sixty people, in and out, and the venue had zero complaints."]],
      gallery: ["Mandap build", "Floral wall", "Lighting design", "Entrance arch"],
      keywords: ["decorator", "wedding decor", "floral design", "stage decor", "event decor"],
    },
  },
  {
    id: "salon",
    label: "Salon & Spa",
    category: "Salon & Spa",
    heroVariant: "split",
    sections: ["services", "gallery", "team", "about", "reviews", "faq", "contact"],
    theme: t({ background: "oklch(0.985 0.01 340)", foreground: "oklch(0.26 0.03 330)", primary: "oklch(0.55 0.12 340)", accent: "oklch(0.88 0.06 330)", accentForeground: "oklch(0.3 0.06 330)", secondary: "oklch(0.96 0.012 340)", muted: "oklch(0.965 0.01 340)", mutedForeground: "oklch(0.52 0.02 330)", border: "oklch(0.9 0.013 340)", ink: "oklch(0.24 0.04 330)", sand: "oklch(0.93 0.035 340)", radius: "1.5rem", displayFont: '"DM Serif Display", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Menu", servicesEyebrow: "Service menu", servicesTitle: "Treatments worth the chair time",
      teamNav: "Stylists", teamEyebrow: "Your stylists", teamTitle: "Hands you can trust",
      galleryTitle: "Inside the salon", aboutTitle: "Why clients rebook",
      contactEyebrow: "Appointments", contactTitle: "Book your slot",
      ctaPrimary: "Book an appointment", ctaSecondary: "Call the salon",
      newsletterTitle: "Offers and new treatments",
    }),
    credibility: ["Sanitised tools", "Cruelty-free products", "Certified colourists", "Bridal packages", "Membership plans"],
    seed: {
      tagline: "Looking after you, properly",
      blurb: "Colour specialists, skin therapy and a chair you're never rushed out of.",
      audience: "Clients who want a stylist who remembers their hair history and never oversells.",
      usp: ["Colour consultation included", "Cruelty-free products", "No upselling policy", "Membership pricing"],
      trust: [["Clients", "18,000+"], ["Rating", "4.8 / 5"], ["Years", "9"], ["Stylists", "12"]],
      services: [
        ["Cut & Style", "Consultation, wash, precision cut and finish.", "₹1,200", "60 min"],
        ["Global Colour", "Ammonia-free colour with bond protection.", "₹4,500", "2 hours"],
        ["Balayage & Highlights", "Hand-painted dimension by a certified colourist.", "₹7,500", "3 hours"],
        ["Facials & Skin", "Medi-grade facials matched to your skin analysis.", "₹2,800", "75 min"],
        ["Bridal Package", "Trial, day-of hair and makeup, plus family styling.", "₹35,000", "Full day"],
        ["Spa Therapies", "Deep tissue, aroma and foot reflexology.", "₹2,200", "60 min"],
      ],
      team: [
        ["Rhea Kapoor", "Creative Director", "L'Oréal Certified", "13 years", "Colour specialist trained in London and Mumbai."],
        ["Jaideep Singh", "Senior Stylist", "Toni & Guy Academy", "9 years", "Known for precision cuts on curly and wavy hair."],
        ["Maya Dsouza", "Skin Therapist", "CIDESCO", "7 years", "Builds long-term skin plans, not one-off facials."],
      ],
      faqs: [
        ["Do I need an appointment?", "Walk-ins are welcome, but weekends fill up by Thursday."],
        ["Which products do you use?", "Ammonia-free, cruelty-free professional lines only."],
        ["Do you offer memberships?", "Yes — a prepaid membership saves roughly twenty percent."],
      ],
      reviewSummary: "Clients mention colour that lasts, stylists who listen and a team that never pushes extra services.",
      reviews: [["Tanvi S.", "First salon that talked me out of a service I didn't need."], ["Neeraj B.", "My balayage still looks good four months later."]],
      gallery: ["Styling floor", "Colour bar", "Spa room", "Reception"],
      keywords: ["salon", "hair colour", "spa", "bridal makeup", "facial"],
    },
  },
  {
    id: "gym",
    label: "Gym & Fitness",
    category: "Fitness Studio",
    heroVariant: "full",
    sections: ["services", "team", "gallery", "about", "reviews", "faq", "contact"],
    theme: t({ background: "oklch(0.15 0.008 250)", foreground: "oklch(0.97 0.005 250)", primary: "oklch(0.85 0.2 130)", primaryForeground: "oklch(0.15 0.008 250)", accent: "oklch(0.78 0.16 60)", accentForeground: "oklch(0.15 0.008 250)", secondary: "oklch(0.21 0.01 250)", muted: "oklch(0.21 0.01 250)", mutedForeground: "oklch(0.74 0.012 250)", border: "oklch(1 0 0 / 14%)", ink: "oklch(0.11 0.008 250)", sand: "oklch(0.3 0.03 130)", radius: "0.25rem", displayFont: '"Bebas Neue", ui-sans-serif, system-ui, sans-serif' }),
    words: w({
      servicesNav: "Programs", servicesEyebrow: "Programs", servicesTitle: "Training that actually progresses",
      teamNav: "Coaches", teamEyebrow: "Your coaches", teamTitle: "Coaches who count your reps",
      galleryTitle: "The floor", aboutTitle: "Why members stay",
      contactEyebrow: "Trial", contactTitle: "Book a free trial",
      ctaPrimary: "Book a free trial", ctaSecondary: "Call the gym",
      newsletterTitle: "Training tips, weekly",
    }),
    credibility: ["Open 5am–11pm", "Certified coaches", "Body composition scans", "Physio on call", "No lock-in contracts"],
    seed: {
      tagline: "Strength, built on a plan",
      blurb: "Coached strength and conditioning in a floor that's never overcrowded, with programming that adapts monthly.",
      audience: "People who've bounced off big-box gyms and want coaching, structure and measurable progress.",
      usp: ["Programmed, not random", "Capped class sizes", "Monthly progress reviews", "No lock-in"],
      trust: [["Members", "1,400"], ["Coaches", "9"], ["Sq ft", "8,000"], ["Rating", "4.9 / 5"]],
      services: [
        ["Strength Programming", "Individual plan, progressed and reviewed every four weeks.", "₹6,500", "Per month"],
        ["Group Classes", "Capped at twelve — HIIT, mobility and conditioning.", "₹3,500", "Per month"],
        ["Personal Training", "One-to-one coaching with nutrition guidance.", "₹1,200", "Per session"],
        ["Body Composition", "InBody scan with a written interpretation.", "₹500", "20 min"],
        ["Rehab & Mobility", "Physio-led return-to-training programming.", "₹1,500", "Per session"],
        ["Corporate Memberships", "Team plans with quarterly health reporting.", "On request", "Custom"],
      ],
      team: [
        ["Vikram Rathod", "Head Coach", "NSCA-CSCS", "12 years", "Powerlifting background, obsessed with movement quality."],
        ["Alisha Pinto", "Conditioning Coach", "ACSM Certified", "8 years", "Runs the classes everyone books out first."],
        ["Dr. Sameer Kale", "Sports Physio", "MPT, Sports", "10 years", "Keeps members training through niggles instead of stopping."],
      ],
      faqs: [
        ["Is there a lock-in?", "No. Monthly memberships, cancel any time."],
        ["I'm a complete beginner.", "Perfect. Everyone starts with an assessment and a four-week base plan."],
        ["Do you have showers?", "Yes — full locker rooms with towels included."],
      ],
      reviewSummary: "Members mention real coaching, uncrowded floors and progress they can actually see in their numbers.",
      reviews: [["Rohit D.", "First gym where a coach corrected my deadlift instead of watching."], ["Ankita J.", "Down 9kg and stronger than I've ever been."]],
      gallery: ["Strength floor", "Class studio", "Recovery zone", "Locker rooms"],
      keywords: ["gym", "fitness", "personal training", "strength training", "classes"],
    },
  },
  {
    id: "lawyer",
    label: "Law Firm",
    category: "Law Firm",
    heroVariant: "editorial",
    sections: ["services", "team", "about", "reviews", "faq", "gallery", "contact"],
    theme: t({ background: "oklch(0.98 0.005 250)", foreground: "oklch(0.2 0.03 255)", primary: "oklch(0.32 0.06 255)", accent: "oklch(0.75 0.1 80)", accentForeground: "oklch(0.24 0.04 60)", secondary: "oklch(0.95 0.008 250)", muted: "oklch(0.955 0.006 250)", mutedForeground: "oklch(0.48 0.02 255)", border: "oklch(0.89 0.008 250)", ink: "oklch(0.18 0.03 255)", sand: "oklch(0.91 0.03 80)", radius: "0.25rem", displayFont: '"Playfair Display", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Practice areas", servicesEyebrow: "Practice areas", servicesTitle: "Counsel across the matters that matter",
      teamNav: "Advocates", teamEyebrow: "Our advocates", teamTitle: "Advocates on your side",
      galleryTitle: "Our chambers", aboutTitle: "Why clients instruct us",
      contactEyebrow: "Consultations", contactTitle: "Request a consultation",
      ctaPrimary: "Request a consultation", ctaSecondary: "Call chambers",
      newsletterTitle: "Legal updates, monthly",
    }),
    credibility: ["Bar Council registered", "Confidentiality assured", "Fixed-fee options", "High Court practice", "Documented advice"],
    seed: {
      tagline: "Clear counsel, carefully argued",
      blurb: "A litigation and advisory practice known for candid advice and meticulous paperwork.",
      audience: "Individuals and businesses who want to know their real position before they spend a rupee on litigation.",
      usp: ["Written opinions", "Fixed-fee advisory", "Direct partner access", "No inflated timelines"],
      trust: [["Matters", "2,300+"], ["Years", "24"], ["Advocates", "8"], ["Courts", "High Court"]],
      services: [
        ["Civil & Commercial Litigation", "Suits, appeals and arbitration across trial and appellate courts.", "On consultation", "Per matter"],
        ["Property & Conveyancing", "Title diligence, agreements and registration support.", "₹25,000", "Per matter"],
        ["Family & Matrimonial", "Divorce, custody and settlement negotiation handled discreetly.", "₹30,000", "Per matter"],
        ["Corporate Advisory", "Contracts, compliance and structuring for growing businesses.", "₹40,000", "Retainer"],
        ["Criminal Defence", "Bail, trial and appellate representation.", "On consultation", "Per matter"],
        ["Consumer & Recovery", "Consumer forum matters and cheque bounce recovery.", "₹18,000", "Per matter"],
      ],
      team: [
        ["Adv. Rajeev Menon", "Managing Partner", "LL.M, Commercial Law", "24 years", "Appears regularly before the High Court in commercial disputes."],
        ["Adv. Shalini Deshpande", "Partner, Family Law", "LL.B", "16 years", "Known for settling matters that others take to trial."],
        ["Adv. Farhan Ali", "Associate Partner", "LL.M, Criminal Law", "11 years", "Handles bail and trial work with meticulous preparation."],
      ],
      faqs: [
        ["What does a first consultation cost?", "A flat fee, adjusted against your matter if you instruct us."],
        ["Will I speak to a partner?", "Yes. Every matter has a named partner accountable for it."],
        ["How long will my case take?", "We give a realistic range in writing after reviewing your papers."],
      ],
      reviewSummary: "Clients note candid advice, written clarity and a practice that discourages litigation when settlement is smarter.",
      reviews: [["Harish P.", "They told me not to file. Saved me two years and a lot of money."], ["Rehana M.", "Every document was ready before every date."]],
      gallery: ["Chambers", "Conference room", "Library", "Reception"],
      keywords: ["lawyer", "advocate", "law firm", "legal consultation", "litigation"],
    },
  },
  {
    id: "architect",
    label: "Architect",
    category: "Architecture Studio",
    heroVariant: "editorial",
    sections: ["gallery", "services", "about", "team", "reviews", "faq", "contact"],
    theme: t({ background: "oklch(0.965 0.003 100)", foreground: "oklch(0.2 0.005 100)", primary: "oklch(0.63 0.17 45)", accent: "oklch(0.55 0.01 100)", accentForeground: "oklch(0.98 0 0)", secondary: "oklch(0.93 0.004 100)", muted: "oklch(0.935 0.003 100)", mutedForeground: "oklch(0.46 0.006 100)", border: "oklch(0.86 0.004 100)", ink: "oklch(0.18 0.005 100)", sand: "oklch(0.88 0.02 80)", radius: "0rem", displayFont: '"Space Grotesk", ui-sans-serif, system-ui, sans-serif' }),
    words: w({
      servicesNav: "Services", servicesEyebrow: "Scope", servicesTitle: "From site study to handover",
      teamNav: "Studio", teamEyebrow: "The studio", teamTitle: "Who you'll work with",
      galleryNav: "Projects", galleryTitle: "Selected projects", aboutTitle: "How we practise",
      contactEyebrow: "Enquiries", contactTitle: "Start a project",
      ctaPrimary: "Start a project", ctaSecondary: "Call the studio",
      newsletterTitle: "Project notes, twice a year",
    }),
    credibility: ["COA registered", "Vaastu-aware planning", "3D walkthroughs", "Green building certified", "Site supervision included"],
    seed: {
      tagline: "Buildings that age well",
      blurb: "A studio practising restrained, climate-aware architecture across homes, workplaces and hospitality.",
      audience: "Clients building once and wanting it done with rigour, not decoration.",
      usp: ["Climate-first planning", "Detailed working drawings", "Fortnightly site visits", "Costed at design stage"],
      trust: [["Projects", "120+"], ["Sq ft built", "2.4M"], ["Years", "18"], ["Awards", "6"]],
      services: [
        ["Residential Architecture", "Homes, villas and apartment interiors from concept to handover.", "₹150 / sq ft", "9–18 months"],
        ["Commercial & Workplace", "Offices and retail with fit-out documentation.", "₹120 / sq ft", "6–12 months"],
        ["Interior Design", "Furniture, joinery and lighting design, fully detailed.", "₹200 / sq ft", "4–8 months"],
        ["Site & Feasibility Study", "Zoning, FSI and massing options before you commit.", "₹75,000", "3 weeks"],
        ["3D Visualisation", "Photoreal walkthroughs for approvals and marketing.", "₹1,20,000", "2 weeks"],
        ["Project Management", "Tendering, contractor coordination and site supervision.", "8% of cost", "Full term"],
      ],
      team: [
        ["Ar. Nandini Rao", "Principal Architect", "M.Arch, CEPT", "18 years", "Leads design across residential and hospitality work."],
        ["Ar. Kunal Shah", "Associate, Technical", "B.Arch", "12 years", "Owns detailing, specifications and site quality."],
        ["Ira Bansal", "Interior Lead", "Interior Architecture", "9 years", "Designs joinery down to the hinge."],
      ],
      faqs: [
        ["What are your fees?", "A percentage of project cost, or per square foot — quoted after the first site visit."],
        ["Do you supervise construction?", "Yes, fortnightly as standard and weekly during critical phases."],
        ["Can you work with my contractor?", "Certainly, provided they work to our drawings and specifications."],
      ],
      reviewSummary: "Clients mention drawings that contractors could actually build from and budgets that held through construction.",
      reviews: [["Suresh N.", "The detailing meant zero site confusion. Rare."], ["Priyanka L.", "The house is cooler than any home we've lived in. That was the brief."]],
      gallery: ["Courtyard house", "Workplace fit-out", "Material study", "Site progress"],
      keywords: ["architect", "architecture studio", "home design", "interior architecture"],
    },
  },
  {
    id: "interior",
    label: "Interior Designer",
    category: "Interior Design Studio",
    heroVariant: "editorial",
    sections: ["gallery", "services", "about", "team", "reviews", "faq", "contact"],
    theme: t({ background: "oklch(0.975 0.012 70)", foreground: "oklch(0.25 0.02 50)", primary: "oklch(0.55 0.1 45)", accent: "oklch(0.82 0.05 120)", accentForeground: "oklch(0.28 0.04 120)", secondary: "oklch(0.945 0.018 70)", muted: "oklch(0.95 0.014 70)", mutedForeground: "oklch(0.5 0.018 50)", border: "oklch(0.89 0.018 70)", ink: "oklch(0.23 0.03 50)", sand: "oklch(0.91 0.04 65)", radius: "1rem", displayFont: '"DM Serif Display", ui-serif, Georgia, serif' }),
    words: w({
      servicesNav: "Services", servicesEyebrow: "How we work", servicesTitle: "Interiors, detailed properly",
      teamNav: "Studio", teamTitle: "The design team", galleryNav: "Projects", galleryTitle: "Recent interiors",
      aboutTitle: "Why clients hand us the keys", contactEyebrow: "Enquiries", contactTitle: "Book a design consult",
      ctaPrimary: "Book a consult", ctaSecondary: "Call the studio",
      newsletterTitle: "Interiors and ideas, monthly",
    }),
    credibility: ["Fixed-cost estimates", "In-house carpentry", "45-day turnkey homes", "Material warranty", "3D before build"],
    seed: {
      tagline: "Homes that feel finished, not decorated",
      blurb: "Turnkey interiors with honest estimates, real materials and a site team that hits the handover date.",
      audience: "Homeowners who want one accountable studio instead of chasing five contractors.",
      usp: ["Fixed-cost estimate", "Own carpentry unit", "Weekly site updates", "Ten-year warranty"],
      trust: [["Homes", "310+"], ["On-time handover", "94%"], ["Years", "12"], ["Rating", "4.9 / 5"]],
      services: [
        ["Turnkey Home Interiors", "Design, execution and styling handed over ready to live in.", "₹1,500 / sq ft", "45–90 days"],
        ["Modular Kitchens", "German hardware, moisture-resistant cores, ten-year warranty.", "₹2,20,000", "3 weeks"],
        ["Wardrobes & Storage", "Bespoke joinery designed around what you actually own.", "₹1,400 / sq ft", "2 weeks"],
        ["Office Interiors", "Workspaces designed for acoustics, light and headcount growth.", "₹1,200 / sq ft", "6–10 weeks"],
        ["Renovation", "Structured refresh of kitchens, baths and living spaces.", "On estimate", "Varies"],
        ["Styling & Furnishing", "Furniture, art and soft furnishing curation.", "₹1,50,000", "2 weeks"],
      ],
      team: [
        ["Aisha Verma", "Principal Designer", "Interior Design, NID", "12 years", "Leads concept and material direction for every project."],
        ["Rohit Salvi", "Site & Execution Head", "Civil Engineering", "14 years", "Runs the workshop and every site to the day."],
        ["Meher Contractor", "Styling Lead", "Design", "7 years", "Sources the pieces that make a house feel lived in."],
      ],
      faqs: [
        ["Is the estimate really fixed?", "Yes, unless you change scope. Every line item is quoted upfront."],
        ["How long does a 2BHK take?", "Typically forty-five to sixty days from design freeze."],
        ["Do you provide warranty?", "Ten years on modular units, one year on all site work."],
      ],
      reviewSummary: "Clients highlight the fixed estimates, weekly site photos and a handover that genuinely happened on time.",
      reviews: [["Nitin & Radha", "Quoted in March, moved in June. Not a rupee over."], ["Sheetal K.", "The kitchen is better than the render, which never happens."]],
      gallery: ["Living room", "Modular kitchen", "Master bedroom", "Material palette"],
      keywords: ["interior designer", "home interiors", "modular kitchen", "turnkey interiors"],
    },
  },
  {
    id: "school",
    label: "School",
    category: "School",
    heroVariant: "split",
    sections: ["about", "services", "team", "gallery", "reviews", "faq", "contact"],
    theme: t({ background: "oklch(0.985 0.006 250)", foreground: "oklch(0.24 0.03 260)", primary: "oklch(0.48 0.15 260)", accent: "oklch(0.85 0.14 90)", accentForeground: "oklch(0.28 0.06 80)", secondary: "oklch(0.955 0.012 250)", muted: "oklch(0.96 0.01 250)", mutedForeground: "oklch(0.5 0.02 260)", border: "oklch(0.895 0.012 250)", ink: "oklch(0.22 0.04 260)", sand: "oklch(0.92 0.06 90)", radius: "1.25rem", displayFont: '"Sora", ui-sans-serif, system-ui, sans-serif' }),
    words: w({
      servicesNav: "Academics", servicesEyebrow: "Academics", servicesTitle: "A curriculum built around curiosity",
      teamNav: "Faculty", teamEyebrow: "Faculty", teamTitle: "Teachers who know every child",
      galleryNav: "Campus", galleryTitle: "Around the campus", aboutTitle: "Why parents choose us",
      contactEyebrow: "Admissions", contactTitle: "Enquire about admissions",
      ctaPrimary: "Apply for admission", ctaSecondary: "Call the office",
      newsletterTitle: "School newsletter",
    }),
    credibility: ["CBSE affiliated", "1:18 teacher ratio", "Transport across 14 routes", "Smart classrooms", "Counsellor on campus"],
    seed: {
      tagline: "Where children are known by name",
      blurb: "A CBSE school with small classes, strong fundamentals and a campus built for play as much as study.",
      audience: "Parents looking for academic rigour without turning childhood into a coaching class.",
      usp: ["1:18 teacher ratio", "No-homework primary years", "Sports every day", "Full-time counsellor"],
      trust: [["Students", "1,250"], ["Faculty", "78"], ["Years", "27"], ["Board average", "89%"]],
      services: [
        ["Pre-Primary", "Play-led foundation years focused on language and motor skills.", "₹68,000", "Per year"],
        ["Primary (I–V)", "Concept-first learning with continuous assessment.", "₹92,000", "Per year"],
        ["Middle School (VI–VIII)", "Labs, projects and the first real taste of specialisation.", "₹1,08,000", "Per year"],
        ["Secondary (IX–X)", "CBSE board preparation with structured mentoring.", "₹1,25,000", "Per year"],
        ["Sports Academy", "Cricket, football, swimming and athletics coaching.", "Included", "Daily"],
        ["Transport", "GPS-tracked buses across fourteen routes.", "₹24,000", "Per year"],
      ],
      team: [
        ["Mrs. Latha Krishnan", "Principal", "M.Ed", "28 years", "Believes every child should be known by name by the principal."],
        ["Mr. Devesh Pandey", "Head of Academics", "M.Sc, B.Ed", "19 years", "Rebuilt the science curriculum around lab-first learning."],
        ["Ms. Fiona D'Souza", "Student Counsellor", "M.A, Psychology", "11 years", "Runs the wellbeing programme across all grades."],
      ],
      faqs: [
        ["When do admissions open?", "Applications open in October for the following academic year."],
        ["What is the class size?", "Capped at thirty-two, with a 1:18 teacher ratio."],
        ["Is transport available?", "Yes — fourteen GPS-tracked routes across the city."],
      ],
      reviewSummary: "Parents mention approachable teachers, real communication and children who actually want to go to school.",
      reviews: [["Anjali M.", "The class teacher calls before we ever have to. That says everything."], ["Prakash R.", "Strong academics without the pressure cooker."]],
      gallery: ["Campus", "Science lab", "Library", "Sports ground"],
      keywords: ["school", "cbse school", "admissions", "primary school"],
    },
  },
  {
    id: "coaching",
    label: "Coaching Classes",
    category: "Coaching Institute",
    heroVariant: "split",
    sections: ["services", "reviews", "team", "about", "gallery", "faq", "contact"],
    theme: t({ background: "oklch(0.985 0.006 275)", foreground: "oklch(0.22 0.03 275)", primary: "oklch(0.45 0.17 275)", accent: "oklch(0.83 0.15 75)", accentForeground: "oklch(0.28 0.06 70)", secondary: "oklch(0.955 0.012 275)", muted: "oklch(0.96 0.01 275)", mutedForeground: "oklch(0.5 0.02 275)", border: "oklch(0.895 0.012 275)", ink: "oklch(0.2 0.04 275)", sand: "oklch(0.92 0.06 75)", radius: "1rem", displayFont: '"Sora", ui-sans-serif, system-ui, sans-serif' }),
    words: w({
      servicesNav: "Courses", servicesEyebrow: "Courses", servicesTitle: "Programmes built around the actual exam",
      teamNav: "Faculty", teamEyebrow: "Faculty", teamTitle: "Teachers who've cracked it themselves",
      galleryNav: "Campus", galleryTitle: "Our classrooms", aboutTitle: "Why students score here",
      contactEyebrow: "Admissions", contactTitle: "Book a free demo class",
      ctaPrimary: "Book a free demo", ctaSecondary: "Call the institute",
      newsletterTitle: "Exam alerts and study plans",
    }),
    credibility: ["Batch size capped at 30", "Weekly mock tests", "Doubt sessions daily", "Recorded lectures", "Parent progress reports"],
    seed: {
      tagline: "Results built on practice, not promises",
      blurb: "Small batches, weekly testing and faculty who track every student's weak chapters personally.",
      audience: "Students and parents who want measurable progress instead of a crowded hall.",
      usp: ["Batches capped at 30", "Weekly mock analysis", "Daily doubt hours", "Personal mentor per student"],
      trust: [["Selections", "1,800+"], ["Top 100 ranks", "23"], ["Years", "15"], ["Faculty", "24"]],
      services: [
        ["JEE Main & Advanced", "Two-year integrated programme with weekly testing.", "₹1,45,000", "2 years"],
        ["NEET", "Biology-heavy programme with NCERT mastery drills.", "₹1,30,000", "2 years"],
        ["Foundation (VIII–X)", "Board plus olympiad preparation from the basics.", "₹65,000", "Per year"],
        ["CET & State Exams", "Focused three-month intensive with state paper drills.", "₹38,000", "3 months"],
        ["Crash Courses", "Eight-week revision with full-length mocks.", "₹28,000", "8 weeks"],
        ["Online Batches", "Live classes with recordings and digital test series.", "₹45,000", "Per year"],
      ],
      team: [
        ["Prof. S. Ramanathan", "Physics Faculty & Director", "M.Sc, IIT Madras", "21 years", "Has mentored twenty-three students into the top hundred."],
        ["Dr. Kavya Menon", "Biology Faculty", "MBBS", "12 years", "Teaches NEET biology the way examiners actually test it."],
        ["Mr. Aakash Jain", "Mathematics Faculty", "M.Sc Mathematics", "14 years", "Known for problem-solving sessions that run past midnight."],
      ],
      faqs: [
        ["Can we attend a demo class?", "Yes — book any weekday and sit through a full session."],
        ["What is the batch size?", "Capped at thirty so faculty can track each student."],
        ["Do you share progress with parents?", "Fortnightly reports plus a call after every mock."],
      ],
      reviewSummary: "Students mention detailed mock analysis, accessible faculty and batches small enough to ask questions in.",
      reviews: [["Aditya K.", "The weekly mock analysis is where my score actually moved."], ["Sneha P.", "Faculty answered doubts on WhatsApp at 11pm before boards."]],
      gallery: ["Classroom", "Doubt session", "Test hall", "Library"],
      keywords: ["coaching classes", "jee coaching", "neet coaching", "tuition"],
    },
  },
  {
    id: "retail",
    label: "Retail Store",
    category: "Retail Store",
    heroVariant: "full",
    sections: ["services", "gallery", "about", "reviews", "faq", "team", "contact"],
    theme: t({ background: "oklch(0.985 0 0)", foreground: "oklch(0.16 0 0)", primary: "oklch(0.16 0 0)", primaryForeground: "oklch(0.99 0 0)", accent: "oklch(0.62 0.22 265)", accentForeground: "oklch(0.99 0 0)", secondary: "oklch(0.955 0 0)", muted: "oklch(0.96 0 0)", mutedForeground: "oklch(0.48 0 0)", border: "oklch(0.89 0 0)", ink: "oklch(0.12 0 0)", sand: "oklch(0.92 0.03 265)", radius: "0.5rem", displayFont: '"Space Grotesk", ui-sans-serif, system-ui, sans-serif' }),
    words: w({
      servicesNav: "Shop", servicesEyebrow: "In store", servicesTitle: "What's on the shelves",
      teamNav: "Team", teamTitle: "The people in store", galleryNav: "Store", galleryTitle: "Inside the store",
      aboutTitle: "Why customers come back", contactEyebrow: "Visit us", contactTitle: "Find us in store",
      ctaPrimary: "Visit the store", ctaSecondary: "Call the store",
      newsletterTitle: "New arrivals and sale alerts",
    }),
    credibility: ["Genuine products only", "Easy exchanges", "Home delivery", "EMI available", "Open all week"],
    seed: {
      tagline: "The shop people recommend",
      blurb: "A neighbourhood store with real stock, fair prices and staff who know the products they sell.",
      audience: "Local customers who'd rather see it, hold it and take it home today.",
      usp: ["Genuine stock, always", "Price-match on request", "Same-day home delivery", "Seven-day exchange"],
      trust: [["Customers", "60,000+"], ["Rating", "4.7 / 5"], ["Years", "19"], ["Brands", "40+"]],
      services: [
        ["New Arrivals", "Fresh stock every week across all categories.", "Varies", "In store"],
        ["Bulk & Corporate Orders", "Volume pricing with GST invoicing.", "On request", "2–5 days"],
        ["Home Delivery", "Same-day delivery within five kilometres.", "Free", "Same day"],
        ["Exchange & Returns", "Seven-day exchange on unused items with the bill.", "Free", "7 days"],
        ["EMI & Finance", "No-cost EMI on purchases above ₹10,000.", "0%", "3–12 months"],
        ["Personal Shopping", "Call ahead and we'll keep it ready at the counter.", "Free", "On request"],
      ],
      team: [
        ["Mahesh Gupta", "Owner", "Retail", "19 years", "Behind the counter almost every day since 2007."],
        ["Sunita Rane", "Store Manager", "Retail Management", "10 years", "Knows the stock better than the inventory system."],
        ["Imran Shaikh", "Customer Care", "Retail", "6 years", "Handles exchanges without making it a negotiation."],
      ],
      faqs: [
        ["Do you deliver?", "Same-day within five kilometres, next-day across the city."],
        ["Can I exchange an item?", "Yes, within seven days with the original bill and packaging."],
        ["Do you offer EMI?", "No-cost EMI on purchases above ₹10,000 on major cards."],
      ],
      reviewSummary: "Customers mention genuine stock, straightforward pricing and staff who don't push a sale.",
      reviews: [["Rakesh V.", "Ordered at noon, delivered by evening. No fuss."], ["Deepa S.", "They exchanged it without a single question."]],
      gallery: ["Store front", "Display shelves", "Billing counter", "New arrivals"],
      keywords: ["store", "shop", "retail", "local shop", "home delivery"],
    },
  },
  {
    id: "home-services",
    label: "Home Services",
    category: "Home Services",
    heroVariant: "split",
    sections: ["services", "about", "reviews", "team", "faq", "gallery", "contact"],
    theme: t({ background: "oklch(0.985 0.008 150)", foreground: "oklch(0.22 0.03 155)", primary: "oklch(0.42 0.11 155)", accent: "oklch(0.85 0.16 95)", accentForeground: "oklch(0.25 0.05 95)", secondary: "oklch(0.955 0.014 150)", muted: "oklch(0.96 0.012 150)", mutedForeground: "oklch(0.48 0.02 155)", border: "oklch(0.895 0.014 150)", ink: "oklch(0.2 0.04 155)", sand: "oklch(0.92 0.06 95)", radius: "0.75rem", displayFont: '"Sora", ui-sans-serif, system-ui, sans-serif' }),
    words: w({
      servicesNav: "Services", servicesEyebrow: "What we fix", servicesTitle: "Jobs done right, first time",
      teamNav: "Technicians", teamEyebrow: "Our technicians", teamTitle: "Verified, trained, on time",
      galleryNav: "Work", galleryTitle: "Recent jobs", aboutTitle: "Why customers call us back",
      contactEyebrow: "Bookings", contactTitle: "Book a technician",
      ctaPrimary: "Book a technician", ctaSecondary: "Call now",
      newsletterTitle: "Maintenance reminders",
    }),
    credibility: ["Police-verified staff", "90-day service warranty", "Upfront pricing", "Same-day slots", "Genuine spares only"],
    seed: {
      tagline: "Reliable hands, same day",
      blurb: "Verified technicians for repairs, deep cleaning and maintenance — priced upfront, warrantied for ninety days.",
      audience: "Households and offices who want a technician who shows up when promised and quotes before working.",
      usp: ["Upfront fixed pricing", "Police-verified technicians", "90-day warranty", "Same-day slots"],
      trust: [["Jobs done", "48,000+"], ["Rating", "4.8 / 5"], ["Technicians", "120"], ["On-time", "96%"]],
      services: [
        ["AC Service & Repair", "Deep jet service, gas top-up and fault diagnosis.", "₹599", "60 min"],
        ["Plumbing", "Leaks, fittings, blockages and bathroom repairs.", "₹399", "45 min"],
        ["Electrical", "Wiring, switchboards, fans and appliance installation.", "₹399", "45 min"],
        ["Deep Cleaning", "Full-home or kitchen and bathroom deep cleans.", "₹2,999", "4 hours"],
        ["Pest Control", "Herbal and chemical treatments with a service guarantee.", "₹1,299", "90 min"],
        ["Painting & Waterproofing", "Interior painting and terrace waterproofing.", "₹18 / sq ft", "2–5 days"],
      ],
      team: [
        ["Suresh Yadav", "Operations Head", "Facility Management", "15 years", "Runs dispatch and holds every technician to the slot."],
        ["Ramesh Pawar", "Senior AC Technician", "ITI Refrigeration", "12 years", "Diagnoses in minutes what others replace blindly."],
        ["Anil Kumar", "Master Electrician", "ITI Electrical", "14 years", "Licensed, meticulous and safety-first on every job."],
      ],
      faqs: [
        ["Do you charge a visit fee?", "A small inspection fee, waived entirely if you approve the work."],
        ["Is there a warranty?", "Ninety days on workmanship and manufacturer warranty on spares."],
        ["How fast can you come?", "Same-day slots in most areas if booked before 4pm."],
      ],
      reviewSummary: "Customers mention on-time arrival, upfront pricing and technicians who explain the fault before fixing it.",
      reviews: [["Vinod A.", "Quoted ₹599, charged ₹599. That's rarer than it should be."], ["Shalini D.", "Booked at 11am, AC was running by 3pm."]],
      gallery: ["AC service", "Deep cleaning", "Electrical work", "Team on site"],
      keywords: ["home services", "ac repair", "plumber", "electrician", "deep cleaning"],
    },
  },
];

export const industryDesigns = ALL;

export const industryMap: Record<string, IndustryDesign> = Object.fromEntries(
  ALL.map((d) => [d.id, d]),
);

export const getIndustryDesign = (id: string): IndustryDesign => industryMap[id] ?? ALL[0]!;

/** CSS custom properties that re-theme the generated site for this vertical. */
export const industryCssVars = (d: IndustryDesign): React.CSSProperties => {
  const th = d.theme;
  return {
    "--background": th.background,
    "--foreground": th.foreground,
    "--card": th.background,
    "--card-foreground": th.foreground,
    "--popover": th.background,
    "--popover-foreground": th.foreground,
    "--primary": th.primary,
    "--primary-foreground": th.primaryForeground,
    "--secondary": th.secondary,
    "--secondary-foreground": th.foreground,
    "--muted": th.muted,
    "--muted-foreground": th.mutedForeground,
    "--accent": th.accent,
    "--accent-foreground": th.accentForeground,
    "--border": th.border,
    "--input": th.border,
    "--ring": th.primary,
    "--ink": th.ink,
    "--sand": th.sand,
    "--radius": th.radius,
    "--font-display": th.displayFont,
    backgroundColor: th.background,
    color: th.foreground,
  } as React.CSSProperties;
};